plugins/admin/admin-plugin.c, plugins/proxy/proxy-plugin.c, src/chassis-mainloop.h, src/mysql-proxy-cli.c, src/network-mysqld.c, src/network-socket.h
=> use reset conn instead of chang user when mysql > 5.7

src/network-mysqld.h
=> Remove tab in network-mysqld.h

plugins/admin/admin-plugin.c, src/chassis-timings.c, src/mysql-proxy-cli.c, src/network-backend.c, src/network-backend.h, src/network-socket.c, src/resultset_merge.c
=> Optimize salt seed supply

plugins/admin/admin-plugin.c, plugins/shard/shard-plugin.c, src/network-mysqld.c, src/network-mysqld.h, src/plugin-common.c, src/resultset_merge.c, src/server-session.c, src/server-session.h, src/shard-plugin-con.c
由于pmd是spockproxy中的MULTIPART_DATA的缩写，目前变量已经改成了server_session_t，变量由此改成ss
=> Change pmd(from spockproxy) to ss

plugins/proxy/proxy-plugin.c, plugins/shard/shard-plugin.c, src/network-mysqld-packet.c, src/network-mysqld-packet.h, src/network-mysqld.c, src/network-mysqld.h, src/plugin-common.c
紧跟5.7时代，抛弃 MySQL old password认证，并解决原先MySQL proxy的小坑
=> Remove MySQL old password

plugins/proxy/proxy-plugin.c, src/cetus-monitor.c, src/network-mysqld.c
=> Don't set master down from monitor,etc

plugins/admin/admin-plugin.c, plugins/proxy/proxy-plugin.c, plugins/shard/shard-plugin.c, src/cetus-log.c, src/cetus-monitor.c, src/chassis-mainloop.h, src/mysql-proxy-cli.c, src/network-conn-pool-wrap.c, src/network-conn-pool.c, src/network-mysqld.c, src/network-mysqld.h, src/network-socket.c, src/network-socket.h
=> Add timeout for idle conn, etc

src/network-conn-pool-wrap.c, src/resultset_merge.c, src/server-session.c
解决tcp stream过程中，由于记录过长导致的session死等问题
=> Fix dead session when tcp streamed

plugins/admin/admin-plugin.c, src/network-mysqld-packet.c, src/server-session.c
=> Add pending event check when prematured returned

src/network-backend.c
=> Fix admin add backend related problems

src/resultset_merge.c
解决tcp stream过程中，部分后端数据库反馈err，而其它数据库正常响应导致的问题
=>  Fix chaos when some backends report err while others not 

plugins/shard/sharding-parser.c, src/sharding-config.c
=> support sharding key type int64

src/character-set.c, src/plugin-common.c
=> Try to fix default charset problems

src/cetus-users.c, src/network-mysqld.c
=> Disable client plugin auth

plugins/proxy/proxy-plugin.c, src/network-conn-pool-wrap.c, src/network-mysqld.h
解决set autocommit = 0使用场景下导致的连接问题
=> Fix set autocommit related problems

plugins/admin/admin-plugin.c
=> 1 remove newfile need not report error 2 add some debug log

plugins/admin/admin-plugin.c
=> fix error:admin command may match incorrectly

plugins/admin/admin-plugin.c
=> fix error:select conn_num from backends

plugins/admin/admin-plugin.c
=> new feature: show maintain status

plugins/admin/admin-plugin.c, src/cetus-util.c, src/network-mysqld.c, src/network-ssl.c
1、admin接口不再支持事务特性
2、修复了编译报警
3、去除了重复代码
=> admin接口不再支持事务特性等

src/plugin-common.c
=> Fix more warnings

plugins/admin/admin-plugin.c
=> fix bug: config set key=val may be wrong

src/network-mysqld.c
添加新的master，删除原先master后，某些情况下会导致访问旧的主库
=> Fix problems related to master removal

plugins/admin/admin-plugin.c
兼容pymysql，并在pymysql设置autocommit=None
=> Compatible with pymysql

src/network-mysqld.c, src/network-mysqld.h
解决 #77 ，并且解决retry_serv_cnt相关问题
=> Fix issue 77 and retry_serv_cnt related problems

plugins/proxy/proxy-plugin.c, plugins/shard/shard-plugin.c, src/network-conn-pool-wrap.c, src/network-mysqld.c, src/network-socket.c, src/network-socket.h, src/plugin-common.c
=> Fix max conn alive time problems

src/network-backend.c, src/network-mysqld.c
=> Auto create connections when add backends

plugins/admin/admin-plugin.c
=> Add read timeout processing for admin

plugins/admin/admin-commands.c, plugins/proxy/proxy-plugin.c, plugins/shard/shard-plugin.c, src/chassis-config.c, src/chassis-config.h, src/chassis-options-utils.c, src/chassis-options-utils.h, src/mysql-proxy-cli.c
add auto save settings and fix some problems
=> auto save settings

plugins/admin/admin-commands.c
=> fix rename problem
